### ISSUE TITLE
There's no border on [Strike Adjuster] button/control ?

### ISSUE THREAD

**Issue by DNS** [AnthonyBradford/optionmatrix#1]
The [Strike Adjuster] have flat button (and no border), so the user cannot distinguish this is a button or just a label.

I believe this is a bug on GTK control. Perhaps there're other alternatives using other GTK control like simple textbox with range [Strike min range] - [Strike max range].

**Comment by AnthonyBradford** [comment]
I wasn't using gtk_button_set_relief(GTK_BUTTON( ... ), GTK_RELIEF_NORMAL);
Now resolved. All the Adjusters in the program have borders now.
