### ISSUE TITLE
Compilation problem on Linux

### ISSUE THREAD

**Issue by agonum** [AnthonyBradford/optionmatrix#4]
I've encountered the following error on Linux Mint:
gtk_display.cpp: In function ‘void file_export(_properties*, char*)’:
gtk_display.cpp:67:14: error: aggregate ‘std::ofstream optionmatrixFileExport’ has incomplete type and cannot be defined
   67 |     ofstream optionmatrixFileExport;

The problem was solved by adding #include <fstream> to gtk_display.cpp

[fstream.patch.txt](https://github.com/AnthonyBradford/optionmatrix/files/13048718/fstream.patch.txt)

**Comment by AnthonyBradford** [comment]
Fixed with commit 997db09.

**Comment by AnthonyBradford** [comment]
Please pull latest commit and try to recompile on Linux Mint again.
